routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/tareas', App\Http\Controllers\TaskController::class);
Route::resource('/proyectos', App\Http\Controllers\ProjectController::class);

Route::get('/cambiar-status/{id}', 'App\Http\Controllers\TaskController@status')->name('tareas.status');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    
    public function tasks()

    {

       return $this->hasMany(Task::class, 'project_id', 'id');

    }

    public function users(){
        
        return $this->belongsToMany(User::class, 'project_user', 'project_id', 'user_id');

    }
    
  
}

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    public function project()

    {

       return $this->belongsTo(Project::class);

    }

    public function user(){

       return $this->belongsTo(User::class, 'user_id', 'id');

       $user_id = User::find($id);
    } 



}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function projects(){
        return $this->belongsToMany(Project::class, 'project_user', 'user_id', 'project_id');
        

    }

    public function tasks(){

        return $this->hasOne(Task::class, 'id', 'user_id');
        

    }
  
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\User;
use App\Models\Task;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    
    public function index()
    {
        $projects = Project::all();

        $users = User::all();

        $tasks = Task::all();

        return view('projects.index')->with('projects', $projects)->with('users', $users)->with('tasks', $tasks);
    }

    
    public function create()
    {
        
    }

    public function store(Request $request)
    {
        $project = new Project;
        $tasks = Task::all();


        $project->name = $request->name;
        $project->status = $request->status;
        $project->description = $request->description;
        $project->sabor = $request->sabor;
        $users = $request->user_id;

        $project->save();
        $project->users()->sync($request->user_id);

        return redirect()->back()->with('users', $users);
    }


    public function show(Project $project)
    {
        //
    }


    public function edit(Project $project)
    {
        //
    }


    public function update(Request $request, Project $project)
    {
        //
    }


    public function destroy(Project $project)
    {
        
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Models\Task;
use App\Models\User;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $tasks = Task::all();

        $users = User::all();

        return view('tasks.index')->with('tasks', $tasks)->with('users', $users);

    }

    
    public function create()
    {
        $users = User::all();

        return view('tasks.create')->with('users', $users);
    }

    
    public function store(Request $request)
    {
        $task = new Task;

        $task->title = $request->title;
        $task->deadline = $request->deadline;
        $task->description = $request->description;
        $task->sabor = $request->sabor;
        $task->is_complete = false;
        $task->project_id = $request->project_id;
        $task->user_id = $request->user_id;

        $task->save();

        $users = User::all();

        Session::flash('exito', 'Se guardó correctamente tu pedido.');
        if($request->source == 'proyectos'){
           return redirect()->route('proyectos.index')->with('users', $users);
        }else{
           return redirect()->route('tareas.index'); 
        }
    }

    
    public function show($id)
    {
        //
    }

    
    public function edit($id)
    {
        $task = Task::find($id);

        return view('tasks.edit')->with('task', $task);
    }

    
    public function update(Request $request, $id)
    {
        $task = Task::find($id);

        $task->title = $request->title;
        $task->deadline = $request->deadline;
        $task->description = $request->description;
        $task->sabor = $request->sabor;

        $task->save();

        Session::flash('info', 'Se editó correcctamente tu pedido.');

        return redirect()->route('tareas.index');
    }

    public function status($id)
    {
        $task = Task::find($id);
        $task->is_complete = true;
        $task->save();

        Session::flash('exito', 'Se ha entregado tu pedido.');

        return redirect()->back();
    }
    
    public function destroy($id)
    {
        $task = Task::find($id);
        $task->delete();

        Session::flash('alert', 'Se eliminó correctamente tu orden.');

        return redirect()->back();
    }
}

resources/views/layouts/_messages.blade.php
@if(Session::has('info'))
<div class="lert alert-info alert-dismissible fade show" role="alert">
  <strong>¡Atención!</strong> {{Session::get('info')}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif

@if(Session::has('alert'))
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>¡Atención!</strong> {{Session::get('alert')}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif


@if(Session::has('exito'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>¡Atención!</strong> {{Session::get('exito')}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif
<script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">


    <!-- Styles -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>
<body>
    

        <main class="py-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                         @include('layouts._messages')
                        </div>
                        </div>
                    </div>
                    @yield('content')
        </main>
    </div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>

resources/views/projects/utilities/_create_modal.blade.php
<div class="modal fade shadow-sm p-3 mb-5 bg-body rounded" id="modalProyectos" role="dialog" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Crear Nuevo Proyecto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <form method="POST" action="{{ route('proyectos.store') }}"> {{ csrf_field() }}
      <div class="modal-body">
        <div class="row">
        	<div class="col-md-8">
        		<div class="form-group">
        			<label>Nombre</label>
        			<input type="text" class="form-control" name="name" required="">
        		</div>
        	</div>
        	<div class="col-md-4">
        		<div class="form-group">
        			<label>Estatus</label>
        			<select class="form-control" name="status">
        				<option value="En Proceso">En Proceso</option>
        				<option value="Terminado">Terminado</option>
        				<option value="Atrasado">Atrasado</option>
        				<option value="Cancelado">Cancelado</option>
        			</select>
        		</div>
        	</div>
      </div>
      <div class="form-group">
      	<label>Descripción</label>
      	<textarea class="form-control" name="description" rows="3"></textarea>
      </div>
			<div class="form-group">
					<label for="exampleFormControlSelect1">Selecciona usuario</label>
					@foreach($users as $user)
					<div class="form-check">
					<input class="form-check-input" type="checkbox" value="{{ $user->id }}" id="defaultCheck1" name="user_id[]">
					{{ $user->name }}
					
					<label class="form-check-label" for="defaultCheck1">
				
					@endforeach
					</label>
			</div>
			
    </div>
    
          </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary">Guardar Proyecto</button>
      </div>
      </form>
    </div>
  </div>
</div>
<script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>

resources/views/projects/utilities/_project_card.blade.php
<div class="card mb-3 rounded-3 ">

	@if($project->status == 'En Proceso')
	<div class="text-white px-2 text-center bg-info">{{ $project->status }}</div>
	@endif


	@if($project->status == 'Terminado')
	<div class="text-white px-2 text-center bg-success">{{ $project->status }}</div>
	@endif


	@if($project->status == 'Atrasado')
	<div class="text-white px-2 text-center bg-warning">{{ $project->status }}</div>
	@endif


	@if($project->status == 'Cancelado')
	<div class="text-white px-2 text-center bg-danger">{{ $project->status }}</div>
	@endif


	<div class="card-body">

		<h5>{{ $project->name }}</h5>
		<p>{{ $project->description }}</p>
		@foreach($project->users as $user)
		<p>{{ $user->name }}</p>
		@endforeach
		<hr>

		<a href="" data-toggle="modal" data-target="#modalCrearTarea_{{ $project->id }}" class="btn btn-outline-dark btn-sm mb-3 rounded-pill">Crear Tarea</a>


		@foreach($project->tasks as $task)
			<div class="d-flex align-items-center justify-content-between">
				<div style="width:60%;">
					<p class="mb-1">{{ $task->title }}</p>
					
					<p class="mb-0">Encargado: {{ $task->user->name }}</p>
					
					@if($task->is_complete == false)
                      <span class="badge badge-warning">Pendiente</span>
                      @else
                      <span class="badge badge-success">Completada</span>
                      @endif
				</div>
			<div>
			@if($task->is_complete == false)
                      <a href="{{ route('tareas.status', $task->id) }}" class="btn btn-outline-success btn-sm" data-toggle="tooltip" data-placement="top" title="Completar"><ion-icon name="checkbox-outline"></ion-icon></a>
                      @endif
                      <a href="{{ route('tareas.edit', $task->id) }}" class="btn btn-outline-info btn-sm" data-toggle="tooltip" data-placement="top" title="Editar"><ion-icon name="create"></ion-icon></a>
                      <form method="POST" style="display: inline-block;" action="{{ route('tareas.destroy', $task->id) }}">
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                          <button type="submit" data-toggle="tooltip" data-placement="top" title="Borrar" class="btn btn-danger btn-sm"><ion-icon name="close-circle-outline"></ion-icon></button>
                      </form>
                      </div>
                </div>
		@endforeach

		<hr>	

		<p>Creado el: {{ Carbon\Carbon::parse($project->created_at)->format('d M Y H:i') }}</p>

	</div>

</div>

<!-- Modal -->
<div class="modal fade rounded-pill" id="modalCrearTarea_{{ $project->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header ">
        <h5 class="modal-title " id="exampleModalLabel">Crear Pastel</h5>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
      </div>
      <form method="POST" action="{{  route('tareas.store')  }}">
      <div class="modal-body">
        {{ csrf_field() }}

        <input type="hidden" name="source" value="proyectos" readonly="">

        <input type="hidden" name="project_id" value="{{ $project->id }}" readonly="">

        <input type="hidden" name="user_id" value="{{ $project->id }}" readonly="">

        <div class="form-group ">
						<label>Nombre de cumpleañero</label>
						<input type="text" name="title" class="form-control" required="">
					</div>

					<div class="form-group">
						<label>Fecha de Cu</label>
						<input type="date" name="deadline" class="form-control">
					</div>

					<div class="form-group">
						<label>Descripción</label>
						<textarea class="form-control" name="description" rows="5"></textarea>
					</div>
					<div class="form-group">
				    <label for="exampleFormControlSelect1">Selecciona usuario</label>
				    <select class="form-control" id="exampleFormControlSelect1" name="user_id">
				    	@foreach($project->users as $user)
				      <option value="{{ $user->id }}">{{ $user->name }}</option>
				        @endforeach
				    </select>
				  </div>
				

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
      </div>
     </form>
    </div>
  </div>
</div>

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="card">
			<div class="card-header">CREAR PASTEL</div>

			<div class="card-body">
				<form method="POST" action="{{  route('tareas.store')  }}">
					{{ csrf_field() }}
					<div class="form-group">
						<label>Nombre del Cumpleañero</label>
						<input type="text" name="title" class="form-control" required="">
					</div>

					<div class="form-group">
						<label>Fecha de Cumpleaños</label>
						<input type="date" name="deadline" class="form-control">
					</div>

					<div class="form-group">
						<label>Especificaciones</label>
						<textarea class="form-control" name="description" rows="5"></textarea>
					</div>

					<div class="form-group">
						<label>Sabor</label>
							<select class="form-select"  name="sabor" aria-label="Default select example">
							<option selected>Selecciona tu sabor</option>
							<option value="Vainilla" id="1">Vainilla</option>
							<option value="Fresa" id="2">Fresa</option>
							<option value="Chocolate" id="3">Chocolate</option>
							</select>
					</div>

					<div class="form-group">
				    <label for="exampleFormControlSelect1">Selecciona usuario</label>
				    <select class="form-control" id="exampleFormControlSelect1" name="user_id">
				    	@foreach($users as $user)
				      <option value="{{ $user->id }}">{{ $user->name }}</option>
				        @endforeach
				    </select>
				  </div>
					<button type="submit" class="btn btn-primary">Guardar Pastel</button>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection
<script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="card">
            <div class="card-header">Editar Pastel</div>

            <div class="card-body">
                <form method="POST" action="{{  route('tareas.update', $task->id)  }}">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    
                    <div class="form-group">

                        <label>Nombre del Cumpleañero</label>
                        <input type="text" name="title" class="form-control" value="{{ $task->title }}" required="">
                   
                    </div>

                    <div class="form-group">

                        <label>Fecha de Cumpleaños</label>
                        <input type="date" name="deadline" class="form-control" value="{{ $task->deadline }}">
                   
                    </div>

                    <div class="form-group">

                        <label>Especificaciones</label>
                        <textarea class="form-control" name="description" rows="5"> {{ $task->description }} </textarea>
                   
                    </div>
                    <div class="form-group">
						<label>Sabor</label>
							<select class="form-select"  name="sabor" aria-label="Default select example">
							<option selected>Selecciona tu sabor</option>
							<option value="1">Vainilla</option>
							<option value="2">Fresa</option>
							<option value="3">Chocolate</option>
							</select>
					</div>
                   
                    
                    <button type="submit" class="btn btn-primary">Actualizar</button>
                    <a href="{{ route('tareas.index') }}" class="btn btn-outline-dark">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
<script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Iconos fontawesome-->       
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">  

<div class="wrapper">
<nav id="sidebar">
         <div class="sidebar-header" href="{{ route('home')}}">
           <a href="{{ route('home')}}"> <img  class="img-fluid michotitulo animate__animated animate__shakeX" src="img/logo.png" >
       </a> </div>

        <ul class="list-unstyled components">
            
            <li>
                <a href="{{ route('home')}}"><i class="fas fa-home"></i> Inicio</a>
            </li>
           
          <li>
                <a href="{{ route('proyectos.index')}}"><i class="fas fa-book-open"></i> Catálogo</a>
            </li>
            <li>
                <a href="{{ route('tareas.index')}}"><i class="fas fa-birthday-cake"></i> Crea tu pastel</a>
            
              </li>
              @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
 <!--<li>
                <a href="#"><i class="far fa-address-book"></i> Contacto</a>-->
        </ul>

    </nav>
<div class="container ">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card shadow p-3 mb-5 bg-body rounded">
                <div class="card-header">PASTELES</div>
                

                <div class="card-body fondowall">
                    <a href="{{  route('tareas.create')  }}" class="btn btn-primary mb-3 rounded-pill"> <ion-icon name="add-circle"></ion-icon> Nuevo Pastel</a>
                </div>
                <table class="table table-sm ">
                  <thead>
                    <tr>
                      
                      <th scope="col">Nombre del Cumpleañero</th>
                      <th scope="col">Fecha de Cumpleaños</th>
                      <th scope="col">Descripción</th>
                      <th scope="col">Sabor</th>
                      <th scope="col">Usuario</th>
                      <th scope="col">Estado</th>
                      
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($tasks as $task)
                    <tr>
                      
                      <td>{{ $task->title }}</td>
                      <td>{{ $task->deadline }}</td>
                      <td>{{ $task->description }}</td>
                      <td>{{ $task->sabor }}</td>
                      <td>{{ $task->user->name }}</td>
                      <td>@if($task->is_complete == false)
                      <span class="badge badge-warning">Entregado </span>
                      @else
                      <span class="badge badge-success">No entregado</span>
                      @endif
                      </td>
                      <td>@if($task->is_complete == false)
                      <a href="{{ route('tareas.status', $task->id) }}" class="btn btn-outline-success btn-sm" data-toggle="tooltip" data-placement="top" title="Completar"><ion-icon name="checkbox-outline"></ion-icon></a>
                      @endif
                      <a href="{{ route('tareas.edit', $task->id) }}" class="btn btn-outline-info btn-sm" data-toggle="tooltip" data-placement="top" title="Editar"><ion-icon name="create"></ion-icon></a>
                      <form method="POST" style="display: inline-block;" action="{{ route('tareas.destroy', $task->id) }}">
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                          <button type="submit" data-toggle="tooltip" data-placement="top" title="Borrar" class="btn btn-danger btn-sm"><ion-icon name="close-circle-outline"></ion-icon></button>
                      </form>
                    </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
@endsection
<script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>

resources/views/tasks/utilities/_tasks_table.blade.php
<tr>
                      <th scope="row">{{ $task->id }}</th>
                      <td>{{ $task->title }}</td>
                      <td>{{ $task->deadline }}</td>
                      <td>{{ $task->description }}</td>
                      <td>{{ $task->sabor }}</td>
                      <td>{{ $task->user_id }}</td>
                      <td>{{ $task->user() }}</td>
                      <td>@if($task->is_complete == false)
                            <span class="badge badge-warning">Pendiente</span>
                            @else
                            <span class="badge badge-success">Completada</span>
                            @endif
                      </td>
                      <td>@if($task->is_complete == false)
                      <a href="{{ route('tareas.status', $task->id) }}" class="btn btn-outline-success btn-sm" data-toggle="tooltip" data-placement="top" title="Completar"><ion-icon name="checkbox-outline"></ion-icon></a>
                      @endif
                      <a href="{{ route('tareas.edit', $task->id) }}" class="btn btn-outline-info btn-sm" data-toggle="tooltip" data-placement="top" title="Editar"><ion-icon name="create"></ion-icon></a>
                      <form method="POST" style="display: inline-block;" action="{{ route('tareas.destroy', $task->id) }}">
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                          <button type="submit" data-toggle="tooltip" data-placement="top" title="Borrar" class="btn btn-danger btn-sm"><ion-icon name="close-circle-outline"></ion-icon></button>
                      </form>
                    </td>
                    </tr>